from typing import Protocol


class Backend(Protocol):
    def request(self, task: dict, attempt: dict) -> dict: ...
    def launch(self, path): ...
    def observe(self, task: dict, attempt: dict) -> dict: ...
    def inspect(self, run_dir) -> dict: ...
